### ISSUE TITLE
How do we want Undo/Redo behave?

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#102]
As discussed in #91 undo/redo may be triggered on Surface level, but actually needs to be interpreted on app level, in the presence of multiple panels (not necessary in single surface scenarios).

I.e., to be able to give visual feedback for an undone change, it might be necessary to open a specific panel.

Having this behavior requires that every document change is able to carry application specific data, which is also interpreted when a change is replayed.

We should discuss here what we want, and what alternatives are there, and for what 'price'.

**Comment by michael** [comment]
I would suggest to trigger this on the controller level:

``` js
controller.executeCommand('undo');
```

Then we can define hooks for undo in the app-specific controller implementation. We considered passing a context when constructing a controlller, that we can then call ctx.setState() on for switching panels etc.

**Comment by obuchtala** [comment]
Or adding `Controller.create(proto)` to create a derived Controller conveniently.
Edit: but that's actually only matter of taste.

**Comment by jacwright** [comment]
For my use-case in [Dabble](http://www.dabblewriter.com/), I want to have undo work similar to IntelliJ's. I'm not defining an implementation but a user-facing description of what happens.

When a user calls undo once, the cursor takes them to the place of the last operation. When calling undo a second time the last operation gets undone. If the cursor is already in place the operation just gets undone. This would allow undo operations to happen across documents or locations within a document while still providing the user insight into what is happening. If you simply undo the last operation the user may not know exactly what was undone if it is off the screen when they call undo.

This may need to be handled by the app, but it will need help from the commands by having them store the last surface and cursor location as well as making that information visible to the app so that it may take the user to that surface/location.

**Comment by obuchtala** [comment]
@jacwright I think that is exactly what we want to do

I think we are all good, as we have undo and redo modeled as ControllerCommand which is working on a app level. So we should be able to achieve all we need.

WIth realtime collab there are some more challenging issues regarding undo in presence of other users' changes - but that is a different story.
