### ISSUE TITLE
Bring back npm git url support

### ISSUE THREAD

**Issue by Integral** [substance/substance#1115]
So not all of us are using NPM `substance` package as a dependency. Some guys are still using git urls as a dependency and there are plenty of reasons to do that.
Since we had `files` directive in `package.json` all things which are not there will be dropped out regardless of what you are using as a dependency: npm package or git url.
...It begins from missing make script and continues with missing directories.
So currently when I using substance as a dependency I have a choice: either use npm package, either go with dirty hacks (like copying or cloning library from somewhere else during post install phase).
It's bad. It's very bad.
Let's change this. Please.

**Comment by rquast** [comment]
I'm doing this too.. pretty nasty hacks but it's not too bad. I use my webpack build to bundle substance without the substance bundler and I've set it up with .gitmodules (see screenshot). Not ideal, but works okay. I create patch files for some of the minor things I need to change (like webpack compatibility).

![substance_git](https://user-images.githubusercontent.com/1103891/29484621-d6178cee-8505-11e7-8f2f-806f27a31d15.png)

I try to regularly keep things updated to the latest commits on the develop branch, so I don't need to spend too much time figuring out what broke (so it's ready for the next version).

When I rollout live code, I have a script that fetches the substance repo if it hasn't already fetched, and run a git pull if it already has. It all works okay because I'm using my webpack bundler rather than the substance bundler.

**Comment by Integral** [comment]
Well, I'm not saying it isn't possible, but I see no reason for this kind of experience ;) At least unless you really have a reason.

**Comment by Integral** [comment]
I'm not sure what was the reason to exclude some files and directories from that list, but if it was just missed, than probably #1118 will fix a problem.
