### ISSUE TITLE
Use a simplified surface transaction API

### ISSUE THREAD

**Issue by michael** [substance/substance#127]
Before:

``` js
surface.transaction({ selection: sel }, function(tx, args) {
  args.annotationType = self.getAnnotationType();
  args.annotationData = self.getAnnotationData();
  args.splitContainerSelections = false;
  args.containerId = self.getContainerId();

  args = transformFn(tx, args);
  result = args.result;
  return args;
});
```

After:

``` js
surface.transaction(sel, function(tx, sel) {
  args.annotationType = self.getAnnotationType();
  args.annotationData = self.getAnnotationData();
  args.splitContainerSelections = false;
  args.containerId = self.getContainerId();

  args = transformFn(tx, args);
  result = args.result;
  return sel;
});
```

We also should improve how transformations should be parametrized (parameter list instead of object) and return values.

**Comment by obuchtala** [comment]
We need to rediscuss this.
I started to implement this simplification, also trying to make arguments of transforms explicit.
However, this turned out to get ugly. The problem is that with explicit arguments, every transform needs to pass through all arguments for all child transforms, making the signatures incredibly large, and again unspecific.

The approach that we taking with transforms is similar to a processing chain, actually considering control flow, it is a processing graph. The simplest way to address this is indeed a state object which is used by the transforms to store and get data from. So I think we have been on the right track already. Though we should think if this can be made more clear.

Shifting this to beta 3.

**Comment by michael** [comment]
Yes, let's shift this.

**Comment by obuchtala** [comment]
It has changed a bit, but still I think transaction API could be improved.
