### ISSUE TITLE
Doc guidelines

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#132]
We are using JSDocs. Find documentation here http://usejsdoc.org/.
Docs are rendered using `npm run doc`
Finally we should add a Docs Guideline to a 'How to contribute' tutorial.

There are some things to be considered so that jsdoc creates the desired output:
- in every 'sub-module' (e.g. 'basics') we put a `@module` declaration into the index.js file: https://github.com/substance/substance/commit/1b0afa73e0334672b1ac153f744ac1b1dbab3be3#diff-23333edbbf1e9d87c7d79217bd9930d4L12
- other modules within the main modules (e.g., basics/oo) should be declared using '/', e.g. Basics/Helpers: https://github.com/substance/substance/commit/1b0afa73e0334672b1ac153f744ac1b1dbab3be3#diff-c3f5846a2605df71445fde36a4c5b03eR10
  
  There is no support for child-modules in jsdoc, so they will not show up automatically within the main modules documentation. However we can document them as properties there: https://github.com/substance/substance/commit/1b0afa73e0334672b1ac153f744ac1b1dbab3be3#diff-c614e68c2023701920b90f24c358a3a9R18
- classes should have a `@class` annotation. To let them show-up within the modules documentation we need to bind them using `@memberof`: https://github.com/substance/substance/commit/1b0afa73e0334672b1ac153f744ac1b1dbab3be3#diff-764613c7e9e3b43466d7382faf0d4f9aR10
- class prototype functions need to be bound to the class using `@memberof`: https://github.com/substance/substance/commit/1b0afa73e0334672b1ac153f744ac1b1dbab3be3#diff-e57a1df2675e7c92dbac37fb85fc5bf3R24
- static class functions should be bound with: https://github.com/substance/substance/commit/1b0afa73e0334672b1ac153f744ac1b1dbab3be3#diff-c67a8a8345dc0f893fce1a0f0c571281R121

**Comment by obuchtala** [comment]
@michael could you do an iteration on Substance.UI documentation?

Edit: use `npm run doc` locally during dev. The docs will be published after merging into master.

**Comment by michael** [comment]
Will do. Nice work on the docs!

**Comment by michael** [comment]
Digging into the docs more. I'm thinking that maybe it would be better to stop aliasing modules in some places. E.g. when looking at the basics module we exposed properties like:

``` js
/**
 * @property {object} OO helper functions for object-oriented programming.
 * @memberof module:Basics
 */
Basics.OO = require('./oo');
```

Not sure how useful that is, because when you look at the docs you just see a teaser for `OO` but no link that is taking you to the actual documentation (except choosing Basics/OO on the navigation pane).

![image](https://cloud.githubusercontent.com/assets/2931/10431418/349aa9ac-7105-11e5-87f3-e5959441ccf5.png)

Would it make sense to use basics/index.js just as an introduction kind of thing with some markdown linking?.

```
In Basics we collect general purpose functions for Substance. Please see individual modules/classes:

- [OO](module-Basics_OO.html) Object Oriented Helpers
- [PathAdapter](module-Basics_PathAdapter.html) Access objects via path
```

Thoughts?

**Comment by Integral** [comment]
Agree!

**Comment by michael** [comment]
I did a first iteration on the UI modules today. See PR #136. I was playing around with JSDoc features and tried to follow some idioms that JSDoc describes. However, those things need to be discussed, as some things may make sense, others are just too strict to be useful. Here's a couple of things that I need your opinion on.

### Module vs. Class

JSDoc differs strictly between modules and classes. We have several places where a class is used as a module too. E.g. if we take Document then according to CommonJS modules there should be a document module that exposes it's classes / properties. So to really conform to this, and also have no collisions with the JSDoc directives we would need to have this structure:

``` js
var Document = require('substance/document').Document;
```

Where 'substance/document' is the module and Document is one class property of that module. _Instead of require('substance/document') returning the Document class directly._

### Module names should conform to the require path.

> The @module tag's value should be the module identifier that's passed to the require() function. For example, if users load the module by calling require('my/shirt'), your JSDoc comment would contain the tag @module my/shirt.

I did this for UI, where i have a `ui` module and a `ui/surface` sub modules.

![image](https://cloud.githubusercontent.com/assets/2931/10464835/fc8ad270-71eb-11e5-96e0-b11250c26295.png)

Should we follow this pattern also for basics? Then we could maybe have a basics module only and expose the helpers via a property. var _ = require('basics').Helpers; However I do see the disadvantage of this CommonJS idiom because you tend to require more than necessary (could bloat the bundle). Also we have to define and maintain all those index.js files.

### Modules as entry points

If we keep the number of modules low we can use these files as entry points for the documentation. I tried this with the `ui/commands` module, by providing a short description and moving on to examples.

http://cdn.substance.io/doc/module-ui_commands.html

Below then is the list of associated classes to dig deeper into the matter. I think this could be a nice approach for top-level documentation.

### Deep linking using namepaths

That's pretty nice actually, we should make use of this to link between different classes / modules in the text but also for the parameter/return types etc. Here's an example: 

http://cdn.substance.io/doc/module-ui_commands.ControllerCommand.html

### Keep number of documented items small

I'd try to not let the class list grow too large. E.g. ToggleStrongCommand is just a 4 liner and does not really need documentation, so i did not register it as a class. What I don't like about most auto-generated docs is that you have lots of dead ends.. like pages where you see almost nothing. I guess we should try to only include a file if can display some useful information.

For ui.commands I only covered the list of supported commands in the top level module documentation as an example.

http://cdn.substance.io/doc/module-ui_commands.html

### Document Component Classes

We should somehow find a way to document all component classes in a different way because with the `@class` directive it suggests that you can create instances with new. However component classes you would use in a render function and supply props. Should we just document a props param for the class? It all feels a bit weird.

http://cdn.substance.io/doc/module-ui_surface.ContainerEditor.html

### Examples

We should include them as much as possible. They really help with understanding and make the API docs more practical. Since examples are possible with JSDoc I wonder if we should make this the only documentation for Substance, since there is also a place for tutorials.

I think we should make discussion soon, talking only the module/file structure. JSDoc statements are fairly repetitive so it's not so easy to move things around without breaking the documentation links.

**Comment by obuchtala** [comment]
Thanks for your discussion. I need to do an iteration having your considerations in mind.

**Comment by michael** [comment]
All clear now with our Substance doc generator.
