### ISSUE TITLE
More coarse-grained undo/redo

### ISSUE THREAD

**Issue by michael** [substance/substance#17]
ATM, every keystroke is wrapped into a document change, making undo redo a bit uncommonly fine-grained.

**Comment by jacwright** [comment]
There is some subtlety to how this ends up working. An easy way is to just group chunks of text by how quickly they were typed together, but this isn't how native OS undo works and isn't the ideal user experience.

It's been awhile since I've been on Windows, but I believe Mac and Windows behave the same way. The rules for Mac are:
- continuous text entry gets collapsed into one command
- continuous text deletion gets collapsed into one command (both backspace and delete together)
- any selection or cursor location change breaks these.
- there are _no_ rules about time between changes.

Examples:
I could type a thousand words in 20 paragraphs without any backspace/delete or cursor changes. When I hit undo all 20 paragraphs would be removed.

I could type a sentence, leave my computer for an hour for lunch, come back to type another sentence, hit undo and both sentences would be removed.

I could type a character, hit ← and then → putting me right back where I was, then type another character. When I hit undo only the second character will be removed. The break occurred because I changed cursor position. The fact that I changed back doesn't matter.

I could place the cursor in the middle of a paragraph. I could press backspace 5 times and delete 5 times removing 10 characters to the right and left of where the cursor was placed. When I press undo, all 10 characters are restored. Although backspace and delete remove characters on different sides of the cursor, they are grouped into one change.

If you get the mechanism for grouping/combining/merging commands together I could look at implementing this. I'm still new in this code-base and don't feel comfortable changing the command mechanism.

**Comment by obuchtala** [comment]
Shifting to beta 5. We will work on real-time collab in beta 5, where this is also a topic.

**Comment by yannisbarlas** [comment]
I'll double the original sentiment that it can be a bit too fine-grained.  
Maybe by keeping the chunks of text that get grouped together short, it won't have much of a jarring effect on the user.  

On the UX side of things, I think this is functionality that users of editors are used to, and it can get a bit tedious for them to `ctrl-z` character by character.
