### ISSUE TITLE
Slow on Firefox when typing fast within Lens

### ISSUE THREAD

**Issue by michael** [substance/substance#356]
Tried rapid typing on OSX Firefox and it feels kind of slow. I did not have the inspector open. Can you confirm that on Windows?

**Comment by obuchtala** [comment]
Hmmm.. what would mean 'kind of slow' now ;)

I don't see a difference on Windows. But might be that you would say that it is kind of slow....
Under windows I always had the feeling that low-level events are not coming in as on your computer. That's why I could never observe any 'rapid typing' problems.

Comparing with other editors, it feels the same as in prosemirror or this editor here on github, not slower.

**Comment by obuchtala** [comment]
Can u please do the same comparison in your FF?

**Comment by obuchtala** [comment]
Turning off preservative rendering in AnnotatedTextComponent increases performance.
Can u plz deactivate that there and see how this changes the speed?

**Comment by obuchtala** [comment]
I disabled preservative rendering of TextProperties for now.
We need to optimize the render implementation first.

**Comment by michael** [comment]
Even without preservative rendering I can observe the lag. It gets worse in paragraphs that have a number of citations inside. However, even for plain text i can see the chars appearing after i stopped typing. It seems really only Firefox is affected. All other browsers update fast with or without preservative rendering.

**Comment by michael** [comment]
It's not really bad and only occurs in FF. Let's look into this again in the next release cycle.

**Comment by obuchtala** [comment]
We improved many things, and introduced new things leading to this problem again.
This seems to be an ongoing chore.
