### ISSUE TITLE
[Question] Implementation of OT Changes

### ISSUE THREAD

**Issue by netsgnut** [substance/substance#53]
Sorry for spamming with issues these days, been starting to play with the current version but at some stage would love some clarifications on the roadmap for future versions.

I am working on a personal wiki system, with a touch of Etherpad in which each page persists automatically over time. In the ideal case, in setting up of a doc, the current text and the revision history are populated from server-side, and one can go back to some point in time and edit that version. If the edited version is not the latest one, a new branch is made. I am also planning to add a tree visualizer for all the branches.

With reference to the current `Document` class implementation, it makes use of two arrays (`done` and `undone`) for each transformations for Undo/Redo. If I am to implement that particular feature here, each transformation should be assigned a unique identifier so that when I do an Undo sequence I would know exactly which revision should I base my following transactions on.

I am not sure if I am trying to reinvent the wheel for this kind of mechanisms here, nor if anything is already covered in our roadmap here. Would appreciate any pointers to the OT mechanism here. Thanks.

**Comment by obuchtala** [comment]
It looks like, what you have in mind is similar to what Git does. There you definitely need SHAs to identify changes.
We are currently moving towards a solution which is similar to what Google Docs does.
There you do not have branches, but every participant (including a server) has a working copy which it applies incoming changes to. The noticable difference to a Git like approach is, that an Undo is not a roll-back (moving backwards) but just applying an inverted operation (moving forwards).
With real-time collab there are some transformations (O**T**) necessary, so that your undo/redos can be applied to the local working copy correctly.
So, altogether, this is a complex topic :)
We will add a real-time collab implementation in the next months. A first running version will hopefully be ready by end of Nov.

HTH

Edit: notice, that the versioning/sync/collab strategy is not implied by OT. OT is just serving low-level capabilities of operations. Git-like versioning, or Google-Wave protocol would be built on top of this.

**Comment by netsgnut** [comment]
Yes, I am aware that this is a very complicated topic :) Before I read how Substance works, I have been reading [ShareJS](http://github.com/share/share). Making OT works right is difficult.

In my use-case though, multiuser session is more like a plus, so while it would be great to have multiple users working on the same document each with consistent local changes, it is not a priority here. However, if our plan here is to implement as a linear revision history then, I think I can change the design docs to reflect that as well. Linear revision history has its advantage of being simpler, too. :)

If I am to pursuit an Etherpad-like application based on current implementation of Substance, I think my best bet is to listen to `document:change` and persist every transformations that I got there, if we can neglect network availability and concurrency issues? Thanks.

**Comment by obuchtala** [comment]
You are right, that would be the way right now.
Be aware that along with the wave implementation we will compress changes so that not every single key-stroke makes a new version. This will be a preparational step, see #17, which I'll implement soon.

**Comment by obuchtala** [comment]
BTW, ShareJS has google wave implemented already, however, the source code is not very ...ehm... maintainable. Substance has a similar implementation on OT side, but not yet the wave prototocol.

**Comment by netsgnut** [comment]
...and that is precisely one of the reasons that I am reluctant in incorporating ShareJS in my own projects. The source code still tends to float around with unclear milestones set. The docs being pretty unclear and obsolete also scares me out.

I think I have one more question too: if I am to persist the undo/redo history, just like what we do for the contents, any existing APIs that I can follow or do we need to change parts of the source code for that? Thanks again.

**Comment by obuchtala** [comment]
Not yet, I am sorry. I could add DocumentChange.toJSON and fromJSON in a branch if you want.

**Comment by netsgnut** [comment]
Would it be part of the Beta 2 milestone? I think it could be useful for others, too.

**Comment by obuchtala** [comment]
Totally!

**Comment by obuchtala** [comment]
#55

**Comment by netsgnut** [comment]
Cool! :heart:

**Comment by obuchtala** [comment]
@netsgnut just to let u know, we are rolling out beta4 with real-time support. Will be continued in beta5.

**Comment by netsgnut** [comment]
Great! Can't wait to try! :)
