### ISSUE TITLE
Selection does not get set when using key bindings.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#75]

**Comment by michael** [comment]
Oh that's actually because of my too smart checker here:

https://github.com/substance/substance/blob/master/ui/controller.js#L194-L199

Should I remove it? Or should we think of another way of triggering the tools to update? I mean semantically, there is no selection change happening...  it has been set to the same value as before. Not sure here.

**Comment by michael** [comment]
Fixed via: https://github.com/substance/substance/commit/5e29388f6aef4efb4c968c3c0dc9d911b48e0c8f
