### ISSUE TITLE
Copy and paste via context menu (access to browser clipboard)

### ISSUE THREAD

**Issue by michael** [substance/substance#853]
Attempted to implement copy and paste via commands + tools and making them available via context menu. This is somewhat important I think as we killed the native context menu, and need to provide some common actions that users expect. Here's the custom context menu from Google Docs:

![image](https://cloud.githubusercontent.com/assets/2931/19390820/1f5196b8-922a-11e6-930b-15d277eb9879.png)

First of all it's good to have control about the context menu, so contenteditable can not mess up the DOM. But then I'm not sure how we can feed the browsers clipboard programmatically.

I started implementing this, but it only works internally. See commit: https://github.com/substance/substance/commit/af9ff94ca0d22ab5dcd9ace125b286c11f39fd4f

**Comment by obuchtala** [comment]
I investigated this a bit:
- copy is possible using `document.execCommand('copy')`.
- paste is not as `document.execCommand('paste')` has been disabled due to security reasons.

I suppose Google Docs is run as a Chrome App, where you can use `document.execCommand('paste')` in so-called background pages.

Making use of an internal clipboard data to enable paste from context menu is IMO not a good idea as it is totally inconsistent. I.e. once data is in the internal clipboard, this will be active, while the system clipboard might have changed.

**Comment by obuchtala** [comment]
Indeed. Google Docs in FF will tell you to use keyboard when clicking the paste menu item.

**Comment by michael** [comment]
Yeah I know the internal clipboard is not a solution. Just had hopes there are ways to access the native one somehow.

What's a pity is that in browser-land by replacing the native context menu we loose something as fundamental as right click + copy/paste. 

Should  I just remove those copy+paste tools for now?

**Comment by johanneswilm** [comment]
Hey guys, yes, this is a known problem, and the clipboard api will be worked over. We discussed it briefly in Lisbon. It will work without execCommand in the next version, and the security restrictions for paste will be less so that i actually becomes usable. I can keep you posted on this issue and make sure that it does what you need.

**Comment by michael** [comment]
Until there's a solution, we exclude that from the context menu.
