### ISSUE TITLE
Sanitization of link

### ISSUE THREAD

**Issue by rquast** [substance/substance#895]
I know it's probably not a high priority for the audience of this project, but has sanitization of input/output been given any consideration before? I gave the link button a go and it doesn't sanitize javascript:alert('hello')

Are there places where we can add this kind of thing as an extension (like in a converter)?

**Comment by michael** [comment]
You know a good/simple sanitation strategy for such cases, without having to depend on an external lib?

**Comment by rquast** [comment]
Not sure. So far I've got a dual strategy where I save the document as both json and html, showing the html to the average user (I sanitize this on the server side before save), but the json goes to the admins when they edit the document. I'm considering something like http://www.php-js.com/ to bridge my backend php to JS so I can reload the json document on the backend and validate it (by extending existing classes) there before saving. Using substance on the backend seems a more straight forward approach than using something like jsonschema. I like the idea of it being isomorphic. Have also considered things like jsonschema, but that's not as easy as the actual code itself (and the ability to plug in your own sanitization library). Something to isomorphically validate the documents, like a validation class where you can plug in your own sanitation library?

**Comment by rquast** [comment]
maybe each package should have a configurable validation interface too? or something along those lines?

**Comment by michael** [comment]
It's important for us to not have any server-side dependencies during editing, as Substance follows an offline-first approach. E.g. the 'backend' could be an XML file on the local filesystem to represent a document. Or you edit the doc while there's no internet connection and sync it later.

I see two different problem domains here:

1) secure the editor so that no scripts can run when you just use the editor
2) secure the final doc that's being published on the web (that's not in the scope of Substance)

If you could provide a sanitization util script I will update the Link package so it does a sanitization before applying the change to the doc.

**Comment by michael** [comment]
A configureable validation interface seems like a bit too much.. I think a util function would do for now.

Apart from link where else would we need this you think?

**Comment by rquast** [comment]
Link is the main one. I'm not sure about anything else.

I don't know much about content security policy, but maybe it will help out in this case (preventing scripts from running): https://content-security-policy.com/

That way if I use that, I can stop editors from using browsers that don't support CSP. This may be an easy fix instead for me.

**Comment by rquast** [comment]
I might close this issue if that's okay and see how things go with CSP. Please reopen if you think it still needs fixing.
