### ISSUE TITLE
Remove or redo quickstart.md, EditorSession state

### ISSUE THREAD

**Issue by Neur0mante** [substance/substance#900]
the [substance/doc/quickstart.md](https://github.com/substance/substance/blob/develop/doc/quickstart.md) example is pretty broken. 
It doesn't import _EditorSession_, it erroneously call `cfg.import(SuperscriptPackage) ` when _SuperscriptPackage_ is already packaged into _ProseEditorPackage_, it uses _configurator_ in place of _cfg_  
```
const cfg = new Configurator()
...
let doc = configurator.createArticle(fixture)
  let editorSession = new EditorSession(doc, {
    configurator: configurator
  })
```
and even when you fix all of that the result is kind of a mess.
Also, it appears to me that _EditorSession_ is only present on the current dev branch obtainable by using ` "substance": "substance/substance#develop"` in the package.json, and then building the project. If I just use `npm install --save substance` I get the older branch with documentSession instead.

**Comment by rquast** [comment]
I noticed all this (and more) too. Looks like they're in the middle of some huge refactoring. I do like the way they've structured everything.. very extensible. Most of the recent commits are tidying things up a lot, but I suspect they're going to change a lot more.

Yesterday I had to figure out how to configure webpack to do the postcss stuff they do without their bundler. Finally figured that out.. now I have to figure out how to rework their reset.css because it mucks around too much with my css.

I've compared the source of both quill and substance.. substance is far better. The features they mention on the front page are exactly why it's a lot better. Can't wait for them to stabilize the code.

**Comment by Integral** [comment]
Hey,
You can find stable beta 5 in master branch.

**Comment by rquast** [comment]
@Integral yup. I think the thing is that the examples use the develop branch (and it's changing frequently).

https://github.com/substance/examples/blob/develop/package.json#L6

Not a big issue for now while things are changing so much though the betas I think.

*edit* ... oh that's because the examples on github default to the develop branch. Okay.. got it :)

**Comment by michael** [comment]
Hey! You are right, lots of things are moving at the moment. If you want to use the lib it's best to stick with the releases and upgrade the code once a new release is out. The reason why we have develop as the default branch is that we ensure PR's are always based on the latest code. We can merge them faster into the unstable branch as opposed to master which actually is the same as the release version. Will add a comment to the README.

**Comment by michael** [comment]
Done. Closing this issue now. Thanks for the feedback!

**Comment by rquast** [comment]
Just a note in case anyone else has a problem with the reset.css. I had to remove the box sizing reset to get things to look normal with my uikit css.

```
*, *:after, *:before {
  -webkit-box-sizing:border-box;
     -moz-box-sizing:border-box;
          box-sizing:border-box;
}
```

(remove that).
